version: '3.1'


services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: flatfinder
      MYSQL_PASSWORD: flatfinder
      MYSQL_DATABASE: flatfinder
    ports:
      - 3306:3306